name: customGroupSystem
version: ${project.version}
main: at.lukas.CustomGroupSystem
api-version: 1.21.11
authors: [Lugges]
description: Playlegend Bewerbungsphase
commands:
  gs:
    description: Group system commands
    usage: /gs <subcommand> [args]
    aliases: [groupsystem, group]

permissions:
  groupsystem.admin.creategroup:
    description: Allows creating new groups
    default: op

  groupsystem.admin.deletegroup:
    description: Allows deleting groups
    default: op

  groupsystem.admin.setpermission:
    description: Allows setting group permissions
    default: op

  groupsystem.admin.listpermissions:
    description: Allows listing group permissions
    default: op

  groupsystem.admin.adduser:
    description: Allows adding users to groups (including temporary groups)
    default: op

  groupsystem.admin.playerinfo:
    description: Allows checking player group information and expiry
    default: true


libraries:
  - com.zaxxer:HikariCP:5.1.0